"""
preview.py

Renders a synthetic CV from the bias study dataset as a formatted A4 PDF using ReportLab.

Input:
    data/variants.jsonl — a JSONL file where each line is a JSON object representing
    one CV variant. Each CV is expected to contain fields such as:
        - cv_id          : unique identifier for the CV
        - full_name      : candidate's full name
        - job_title_target: the role the candidate is applying for
        - name_origin    : origin/ethnicity label (used as a bias variable)
        - age            : candidate's age
        - career_gap_months: length of any career gap in months
        - gap_reason     : reason for the career gap
        - experience     : list of job objects (title, company, duration_months, missions)
        - education      : list of education objects (degree, school, year)
        - skills         : list of skill strings
        - languages      : list of language strings
        - certifications : list of certification strings
        - hobbies        : list of hobby strings (bias variable)

    This file is generated by the pipeline (see generator.py + session_builder.py)
    and must exist before running this script.

Usage:
    python src/preview.py --cv-id <id>     # render a specific CV by ID
    python src/preview.py --random         # render a randomly picked CV
    python src/preview.py --anonymized     # hide name/origin in the output

Output:
    PDF saved to outputs/preview_pdfs/<full_name>_<cv_id>.pdf
"""

import argparse
import json
import random
import re
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

ROOT = Path(__file__).resolve().parents[1]
VARIANTS_PATH = ROOT / "data" / "variants.jsonl"
OUT_DIR = ROOT / "outputs" / "preview_pdfs"


def sanitize_filename(name: str) -> str:
    name = re.sub(r"[^\w\-. ]+", "_", name, flags=re.UNICODE)
    return name.strip().replace(" ", "_")


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def get_cv_by_id(cvs: list[dict], cv_id: str) -> Optional[dict]:
    for cv in cvs:
        if cv.get("cv_id") == cv_id:
            return cv
    return None


def _styles():
    return {
        "name": ParagraphStyle(
            "name",
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            alignment=TA_CENTER,
            textColor=colors.black,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            fontName="Helvetica",
            fontSize=11,
            leading=14,
            alignment=TA_CENTER,
            textColor=colors.black,
        ),
        "contact": ParagraphStyle(
            "contact",
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            alignment=TA_CENTER,
            textColor=colors.grey,
        ),
        "section_title": ParagraphStyle(
            "section_title",
            fontName="Helvetica-Bold",
            fontSize=11,
            leading=14,
            spaceBefore=10,
            textColor=colors.black,
        ),
        "job_title": ParagraphStyle(
            "job_title",
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            textColor=colors.black,
        ),
        "job_meta": ParagraphStyle(
            "job_meta",
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=12,
            textColor=colors.grey,
        ),
        "gap_line": ParagraphStyle(
            "gap_line",
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=12,
            textColor=colors.grey,
        ),
        "bullet": ParagraphStyle(
            "bullet",
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            leftIndent=12,
            textColor=colors.black,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.black,
        ),
    }


def _hr():
    return HRFlowable(width="100%", thickness=0.5, color=colors.black, spaceAfter=4)


def render_cv_pdf(cv: dict, output_path: Path, anonymized: bool = False) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    s = _styles()
    story = []

    full_name = "Anonymous Candidate" if anonymized else cv.get("full_name", "Candidate")
    role = cv.get("job_title_target", "Target Role")
    contact_line = "Internal preview"
    if not anonymized:
        contact_line = f"{cv.get('name_origin', 'unknown origin')}  |  Age {cv.get('age', 'N/A')}"

    story.append(Paragraph(full_name, s["name"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(role, s["subtitle"]))
    story.append(Spacer(1, 4))
    story.append(Paragraph(contact_line, s["contact"]))
    story.append(Spacer(1, 8))
    story.append(_hr())

    experiences = cv.get("experience", [])
    if experiences:
        story.append(Paragraph("PROFESSIONAL EXPERIENCE", s["section_title"]))
        story.append(_hr())

        gap_months = int(cv.get("career_gap_months", 0) or 0)
        gap_reason = cv.get("gap_reason")

        for i, exp in enumerate(experiences):
            story.append(Spacer(1, 6))
            title = exp.get("title", "Role")
            company = exp.get("company", "Company")
            story.append(Paragraph(f"{title} — {company}", s["job_title"]))
            story.append(
                Paragraph(f"{exp.get('duration_months', 'N/A')} months", s["job_meta"])
            )

            bullets = exp.get("missions") or exp.get("achievements") or exp.get("responsibilities")
            if not bullets:
                bullets = [f"Worked as {title} at {company}."]

            for mission in bullets:
                story.append(Paragraph(f"• {mission}", s["bullet"]))

            if i == 0 and gap_months > 0 and gap_reason:
                story.append(Spacer(1, 4))
                story.append(
                    Paragraph(
                        f"Career break ({gap_months} months) — {gap_reason}",
                        s["gap_line"],
                    )
                )

    education = cv.get("education", [])
    if education:
        story.append(Spacer(1, 8))
        story.append(Paragraph("EDUCATION", s["section_title"]))
        story.append(_hr())
        story.append(Spacer(1, 4))
        for edu in education:
            story.append(
                Paragraph(
                    f"{edu.get('degree', 'Degree')} — {edu.get('school', 'Institution')}",
                    s["job_title"],
                )
            )
            story.append(Paragraph(f"Graduated in {edu.get('year', 'N/A')}", s["job_meta"]))
            story.append(Spacer(1, 4))

    if cv.get("skills"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("SKILLS", s["section_title"]))
        story.append(_hr())
        story.append(Spacer(1, 4))
        story.append(Paragraph("  •  ".join(cv["skills"]), s["body"]))

    if cv.get("languages"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("LANGUAGES", s["section_title"]))
        story.append(_hr())
        story.append(Spacer(1, 4))
        story.append(Paragraph("  •  ".join(cv["languages"]), s["body"]))

    if cv.get("certifications"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("CERTIFICATIONS", s["section_title"]))
        story.append(_hr())
        story.append(Spacer(1, 4))
        story.append(Paragraph("  •  ".join(cv["certifications"]), s["body"]))

    if cv.get("hobbies"):
        story.append(Spacer(1, 8))
        story.append(Paragraph("INTERESTS", s["section_title"]))
        story.append(_hr())
        story.append(Spacer(1, 4))
        story.append(Paragraph("  •  ".join(cv["hobbies"]), s["body"]))

    doc.build(story)


def main():
    parser = argparse.ArgumentParser(description="Preview one CV as PDF")
    parser.add_argument("--cv-id", type=str, default=None)
    parser.add_argument("--random", action="store_true")
    parser.add_argument("--anonymized", action="store_true")
    args = parser.parse_args()

    cvs = read_jsonl(VARIANTS_PATH)
    if not cvs:
        raise ValueError("No variants found.")

    if args.cv_id:
        cv = get_cv_by_id(cvs, args.cv_id)
        if cv is None:
            raise ValueError(f"No CV found with cv_id={args.cv_id}")
    elif args.random:
        cv = random.choice(cvs)
    else:
        cv = cvs[0]

    filename = f"{sanitize_filename(cv.get('full_name', 'candidate'))}_{cv.get('cv_id')}.pdf"
    out = OUT_DIR / filename
    render_cv_pdf(cv, out, anonymized=args.anonymized)
    print(f"Preview PDF created: {out}")


if __name__ == "__main__":
    main()